' COCO3 COLOR CHART

' Originally from the Rainbow January 1987 article "Color Chart for Coco3"
' by Rick Adams and Dale Lear

' Altered to fix the palette glitches in the original, 35 years later,
' by Rick Adams

	' Double speed poke
	poke &hffd9, 0

	' Set all palettes to black
	for i = 0 to 15
		palette i, 0
	next i

	' Set video mode
	hscreen 2

	' Foreground for text is white
	palette 1, 63

	' Chart title
	hprint (4, 1), "Color Computer 3 - Color Chart"

	' Four columns
	for x = 0 to 3

		' Draw a box around the entire column
		hline (x * 80 + 10, 31)-(x * 80 + 40, 159), pset, b

		' Color in the column
		hcolor x + 8
		hline (x * 80 + 11, 32)-(x * 80 + 39, 158), pset, bf

		' 16 rows
		hcolor 1
		for y = 0 to 15

			' Display the color number to the right of each cell
			hprint (x * 10 + 5, y + 4), x * 16 + y

			' Draw a line between each cell
			hline (x * 80 + 10, y * 8 + 39)-(x * 80 + 40, y * 8 + 39), pset

		next y

	next x

	' Legend at the bottom
	hprint (7, 22), "Press BREAK key to exit"

	' Poke in some ML code and execute it
	read a, b
	for i = a to b
		read d
		poke i, d
	next i
	exec a

	' These included DATA statements are generated by compiling chart.asm
	include "chart.dat"

